### ISSUE TITLE
I can'nt upload by jbrowse job

### ISSUE THREAD

**Issue by anajulia95** [LyonsLab/coge#76]
Good morning
I would like to upload my jbrowse job in coge genomeevolutions but I don't have enought options like metadata optionsa and developers mode, so I download CoGe and tried to install the whole programs, modules and components. I would like to know how can I upload my genome and annotation in jbrowse to genome evolution coge.
thanks

**Comment by elyons** [comment]
You need to load the genome and annotations through a system that integrated them in CoGe's core data management system.  Instructions for doing this are:

Load Genome (fasta files): https://genomevolution.org/wiki/index.php/How_to_load_genomes_into_CoGe

Load Annotation (GFF files): https://genomevolution.org/wiki/index.php/LoadAnnotation

**Comment by anajulia95** [comment]
@elyons  I know how load my annotations throught genome evolution like you suggest, but can I get developers options in coge to obtain something like this: both the Hierarchical and Faceted track selectors
![imagen_2](https://user-images.githubusercontent.com/49414964/59812755-b17d1f00-92d4-11e9-985d-035cf9b5db42.png)
![imagen_1](https://user-images.githubusercontent.com/49414964/59812768-bc37b400-92d4-11e9-91ab-2aafa4299fbb.png)
