### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by mictadlo** [LyonsLab/coge#78]
Hi,
Do you have any plans to provide a docker container?

Thank you in advance

Michal

**Comment by elyons** [comment]
Hi Michal,

Putting all  of CoGe into a container is not the right thing to do.  It is a massive, multipart system.  We have made VM images of CoGe in the past, but they were not frequently used and took a lot of time to maintain and update.  We also provide an API to coge as well as the ability to embed parts of CoGe into other websites.  

REST API: https://genomevolution.org/wiki/index.php/Web_Services_REST_API
Embedding: https://genomevolution.org/wiki/index.php/Embedding_CoGe_JBrowse_in_your_website

Best,
-eric
